#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pyHMI.Canvas import HMICanvas
from pyHMI.Colors import *
from pyHMI.Dialog import ConfirmDialog
from pyHMI.DS_ModbusTCP import ModbusTCPDevice
from pyHMI.Tag import Tag, tag_equal
import time
import tkinter as tk
from tkinter import ttk


class Devices(object):
    # init datasource
    # PLC TBox
    tbx_api = ModbusTCPDevice('163.111.184.144', port=502, unit_id=2, timeout=2.0, refresh=1.0, debug=False)
    # init modbus tables
    tbx_api.add_bits_table(20800, 96)
    tbx_api.add_floats_table(20900, 32)
    # TODO remove this after 09/2017 (replace by new REG2 tags)
    tbx_api.add_bits_table(21500, 16)
    tbx_api.add_words_table(20588, 24)
    # Reg. L1
    tbx_reg1 = ModbusTCPDevice('163.111.184.147', port=502, unit_id=1, timeout=2.0, refresh=1.0, debug=False)
    tbx_reg1.add_bits_table(20500, 16)
    tbx_reg1.add_floats_table(20700, size=32)
    # Reg. L2
    # tbx_reg2 = ModbusTCPDevice('163.111.184.148', port=502, unit_id=1, timeout=2.0, refresh=1.0, debug=False)
    # tbx_reg2.add_bits_table(20500, 16)
    # tbx_reg2.add_floats_table(20700, size=32)
    # API ratio
    tbx_ratio = ModbusTCPDevice('163.111.184.146', port=502, unit_id=6, timeout=2.0, refresh=1.0, debug=False)
    tbx_ratio.add_floats_table(23000, size=3)


class Tags(object):
    # tags list
    NULL_TAG = Tag(False)
    # Tbox API
    # read bits
    API_POSTE_ARRET = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20800})
    API_L1_ARRET = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20801})
    API_L2_ARRET = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20802})
    API_POSTE_MARCHE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20803})
    API_L1_MARCHE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20804})
    API_L2_MARCHE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20805})
    API_LOCAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20806})
    API_TELE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20807})
    API_MODE_I3 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20808})
    API_MODE_I4 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20809})
    API_MEL_AU = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20810})
    API_PCS_VTL_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20812})
    API_PCS_VTL_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20813})
    API_DEF_MES_CON_L1 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20814})
    API_DEF_MES_CON_L2 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20815})
    API_ANL_GNY_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20816})
    API_ANL_GNY_CAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20817})
    API_ANL_C4_CAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20818})
    API_Q_ANNU_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20820})
    API_RATIO_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20821})
    API_SEC_L1_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20822})
    API_SEC_L2_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20823})
    API_Q_MINE_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20824})
    API_Q_AE_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20825})
    API_Q_AO_INH = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20826})
    API_REL_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20829})
    API_WBE_VTL_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20830})
    API_WBE_VTL_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20831})
    API_WBE_L1_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20832})
    API_WBE_L2_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20833})
    API_WBE_L1_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20834})
    API_WBE_L2_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20835})
    API_PCS_L1_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20836})
    API_PCS_L2_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20837})
    API_PCS_L1_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20838})
    API_PCS_L2_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20839})
    API_Q_AE_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20840})
    API_Q_AE_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20841})
    API_Q_MINE_PP = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20842})
    API_Q_AO_M = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20843})
    API_Q_AO_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20844})
    API_Q_ANNU_MM = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20845})
    API_ANL_SEC_L1_CAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20846})
    API_ANL_SEC_L2_CAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20847})
    API_DEF_EDF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20848})
    API_ABS_U_AV_DJ = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20849})
    API_DEF_CHG_24V = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20850})
    API_ANL_SEC_L1_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20856})
    API_ANL_REG_L1_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20857})
    API_ANL_SEC_L2_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20858})
    API_ANL_REG_L2_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20859})
    API_ANL_C4_DEF = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20860})
    API_ANL_REG_L1_CAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20861})
    API_ANL_REG_L2_CAL = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20862})
    API_DEF_ATD1 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20864})
    API_DEF_ATD2 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20865})
    API_DEF_O2_1 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20866})
    API_DEF_O2_2 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20867})
    API_DEF_FEU_1 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20868})
    API_DEF_FEU_2 = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20869})
    API_AU_DIDG = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20870})
    API_DEF_CENT = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20871})
    API_ETL_CENT = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 20872})
    # read floats
    API_POS_VL1 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20900})
    API_POS_VL2 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20902})
    API_Q_MINE = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20904})
    API_P_MINE = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20906})
    API_P_AO1 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20908})
    API_P_AO2 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20910})
    API_WBE_REG_L1 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20912})
    API_WBE_SEC_L1 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20914})
    API_PCS_L1 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20916})
    API_WBE_REG_L2 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20918})
    API_WBE_SEC_L2 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20920})
    API_PCS_L2 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20922})
    API_Q_ANNU = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20926})
    API_WBE_C4 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20928})
    API_PCS_C4 = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20930})
    API_WBE_GNY = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20932})
    API_PCS_GNY = Tag(0.0, src=Devices.tbx_api, ref={'type': 'float', 'addr': 20934})
    # T-Box Reg L1
    # read bits
    REG1_MARCHE = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20500})
    REG1_ERR_C_WOBBE = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20501})
    REG1_ERR_C_PCS = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20502})
    REG1_ERR_C_DEBIT = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20503})
    REG1_DEF_M_WOBBE = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20504})
    REG1_DEF_M_PCS = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20505})
    REG1_DEF_M_DEBIT = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20506})
    REG1_PID_WOBBE_A = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20507})
    REG1_PID_PCS_A = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20508})
    REG1_PID_DEBIT_A = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20509})
    REG1_INH_M_WOBBE = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20510})
    REG1_INH_M_PCS = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20511})
    REG1_INH_M_DEBIT = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20512})
    REG1_AUTO_D = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20513})
    REG1_AUTO_L = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20514})
    REG1_MANU = Tag(False, src=Devices.tbx_reg1, ref={'type': 'bit', 'addr': 20515})
    # read floats
    REG1_C_WOBBE_ACT = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20700})
    REG1_C_WOBBE_CSR = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20702})
    REG1_C_PCS_ACT = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20704})
    REG1_C_PCS_CSR = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20706})
    REG1_C_DEBIT_ACT = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20708})
    REG1_C_DEBIT_CSR = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20710})
    REG1_M_WOBBE = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20712})
    REG1_M_PCS = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20714})
    REG1_M_DEBIT = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20716})
    REG1_OUT_REG = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20718})
    REG1_OUT_PID_WOBBE = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20720})
    REG1_OUT_PID_PCS = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20722})
    REG1_OUT_PID_DEBIT = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20724})
    REG1_MDV = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'float', 'addr': 20762})
    # virtuals
    REG1_LOCAL = Tag(False, get_cmd=lambda: Tags.REG1_AUTO_L.val or Tags.REG1_MANU.val)
    REG1_ARRET = Tag(False, get_cmd=lambda: tag_equal(Tags.REG1_MARCHE, False))
    REG1_DLT_C_WOBBE = Tag(0.0, get_cmd=lambda: Tags.REG1_C_WOBBE_ACT.e_val - Tags.REG1_M_WOBBE.e_val)
    REG1_DLT_C_PCS = Tag(0.0, get_cmd=lambda: Tags.REG1_C_PCS_ACT.e_val - Tags.REG1_M_PCS.e_val)
    REG1_DLT_C_DEBIT = Tag(0.0, get_cmd=lambda: Tags.REG1_C_DEBIT_ACT.e_val - Tags.REG1_M_DEBIT.e_val)
    # write bits
    REG1_MODE_AUTO = Tag(False, src=Devices.tbx_reg1, ref={'type': 'w_bit', 'addr': 20560})
    REG1_MODE_MANU = Tag(False, src=Devices.tbx_reg1, ref={'type': 'w_bit', 'addr': 20561})
    # write floats
    REG1_W_CONS_W = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'w_float', 'addr': 20780})
    REG1_W_CONS_P = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'w_float', 'addr': 20782})
    REG1_W_CONS_D = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'w_float', 'addr': 20784})
    REG1_W_OUV_VL = Tag(0.0, src=Devices.tbx_reg1, ref={'type': 'w_float', 'addr': 20786})
    # T-Box Reg L2
    # read bits
    REG2_MARCHE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21500})
    REG2_ERR_C_WOBBE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21501})
    REG2_ERR_C_PCS = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21502})
    REG2_ERR_C_DEBIT = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21503})
    REG2_DEF_M_WOBBE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21504})
    REG2_DEF_M_PCS = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21505})
    REG2_DEF_M_DEBIT = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21506})
    REG2_PID_WOBBE_A = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21507})
    REG2_PID_PCS_A = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21508})
    REG2_PID_DEBIT_A = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21509})
    REG2_INH_M_WOBBE = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21510})
    REG2_INH_M_PCS = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21511})
    REG2_INH_M_DEBIT = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21512})
    REG2_AUTO_D = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21513})
    REG2_AUTO_L = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21514})
    REG2_MANU = Tag(False, src=Devices.tbx_api, ref={'type': 'bit', 'addr': 21515})
    # read integers
    REG2_C_WOBBE_ACT = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20588, 'signed': True})
    REG2_C_WOBBE_CSR = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20589, 'signed': True})
    REG2_C_PCS_ACT = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20590, 'signed': True})
    REG2_C_PCS_CSR = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20591, 'signed': True})
    REG2_C_DEBIT_ACT = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20592, 'signed': True})
    REG2_C_DEBIT_CSR = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20593, 'signed': True})
    REG2_M_WOBBE = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20594, 'signed': True})
    REG2_M_PCS = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20595, 'signed': True})
    REG2_M_DEBIT = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20596, 'signed': True})
    REG2_OUT_REG = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20600, 'signed': True, 'span': 0.1})
    REG2_OUT_PID_WOBBE = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20597, 'signed': True, 'span': 0.1})
    REG2_OUT_PID_PCS = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20598, 'signed': True, 'span': 0.1})
    REG2_OUT_PID_DEBIT = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20599, 'signed': True, 'span': 0.1})
    REG2_MDV = Tag(0.0, src=Devices.tbx_api, ref={'type': 'word', 'addr': 20611, 'signed': True})
    # virtuals
    REG2_LOCAL = Tag(False, get_cmd=lambda: Tags.REG2_AUTO_L.val or Tags.REG2_MANU.val)
    REG2_ARRET = Tag(False, get_cmd=lambda: tag_equal(Tags.REG2_MARCHE, False))
    REG2_DLT_C_WOBBE = Tag(0.0, get_cmd=lambda: Tags.REG2_C_WOBBE_ACT.e_val - Tags.REG2_M_WOBBE.e_val)
    REG2_DLT_C_PCS = Tag(0.0, get_cmd=lambda: Tags.REG2_C_PCS_ACT.e_val - Tags.REG2_M_PCS.e_val)
    REG2_DLT_C_DEBIT = Tag(0.0, get_cmd=lambda: Tags.REG2_C_DEBIT_ACT.e_val - Tags.REG2_M_DEBIT.e_val)
    # API ratio
    RATIO_PCS_VTL = Tag(0.0, src=Devices.tbx_ratio, ref={'type': 'float', 'addr': 23000})
    RATIO_WBE_VTL = Tag(0.0, src=Devices.tbx_ratio, ref={'type': 'float', 'addr': 23002})
    RATIO_Q_AE_VTL = Tag(0.0, src=Devices.tbx_ratio, ref={'type': 'float', 'addr': 23004})

    # local (no external source)
    HMI_WORD = Tag(0)

    @classmethod
    def update_tags(cls):
        # update tags
        cls.HMI_WORD.set(cls.HMI_WORD.val + 1)


class HMITab(tk.Frame):
    def __init__(self, notebook, update_ms=500, *args, **kwargs):
        tk.Frame.__init__(self, notebook, *args, **kwargs)
        # global tk app shortcut
        self.notebook = notebook
        self.app = notebook.master
        # frame auto-refresh delay (in ms)
        self.update_ms = update_ms
        # setup auto-refresh of notebook tab (on-visibility and every update_ms)
        self.bind('<Visibility>', lambda evt: self.tab_update())
        self._tab_update()

    def _tab_update(self):
        if self.winfo_ismapped():
            self.tab_update()
        self.master.after(self.update_ms, self._tab_update)

    def tab_update(self):
        pass


class TabSyno(HMITab):
    def __init__(self, notebook, update_ms=500, *args, **kwargs):
        HMITab.__init__(self, notebook, update_ms, *args, **kwargs)
        # tab "interconnexion"
        self.map_int = HMICanvas(self, width=800, height=550, debug=False)
        # add button
        self.map_int.add_button('AVION_DN200', 100, 50, text='DN200 Avion', state='disabled',
                                disabledforeground=BLACK, borderwidth=0)
        self.map_int.add_button('AO', 550, 500, text='AO', state='disabled',
                                disabledforeground=BLACK, borderwidth=0)
        self.map_int.add_button('B_ASP', 250, 500, text='Aspiration', state='disabled',
                                disabledforeground=BLACK, borderwidth=0)
        # add simple valve
        self.map_int.add_s_valve('V12', 400, 350, label='V12', zoom=0.6, align='h')
        # add motor valve
        self.map_int.add_s_valve('B0', 350, 50, label='B0', zoom=0.8, align='h')
        self.map_int.add_s_valve('B1', 550, 200, label='B1', zoom=0.8, align='v')
        self.map_int.add_s_valve('B2', 250, 200, label='B2', zoom=0.8, align='v')
        self.map_int.add_s_valve('SII4', 550, 425, label='SII4', zoom=0.8, align='v')
        self.map_int.add_s_valve('SII3', 250, 425, label='SII3', zoom=0.8, align='v')
        # add flow valve
        self.map_int.add_f_valve('VL1', 550, 275, label='VL1', zoom=0.8, align='v')
        self.map_int.add_f_valve('VL2', 250, 275, label='VL2', zoom=0.8, align='v')
        # add point
        self.map_int.add_point('p1', 400, 150)
        self.map_int.add_point('p2', 250, 150)
        self.map_int.add_point('p3', 550, 150)
        self.map_int.add_point('p4', 250, 350)
        self.map_int.add_point('p5', 550, 350)
        # add pipes
        self.map_int.add_pipe('t1', from_name='AVION_DN200', to_name='P_AVION')
        self.map_int.add_pipe('t2', from_name='P_AVION', to_name='B0')
        self.map_int.add_pipe('t3', from_name='Q_AVION', to_name='B0')
        self.map_int.add_pipe('t4', from_name='Q_AVION', to_name='p1')
        self.map_int.add_pipe('t5', from_name='p1', to_name='p2')
        self.map_int.add_pipe('t6', from_name='p1', to_name='p3')
        self.map_int.add_pipe('t7', from_name='p2', to_name='B2')
        self.map_int.add_pipe('t8', from_name='p3', to_name='B1')
        self.map_int.add_pipe('t9', from_name='B1', to_name='VL1')
        self.map_int.add_pipe('t10', from_name='B2', to_name='VL2')
        self.map_int.add_pipe('t11', from_name='VL1', to_name='p5')
        self.map_int.add_pipe('t12', from_name='VL2', to_name='p4')
        self.map_int.add_pipe('t13', from_name='p4', to_name='V12')
        self.map_int.add_pipe('t14', from_name='p5', to_name='V12')
        self.map_int.add_pipe('t15', from_name='p4', to_name='SII3')
        self.map_int.add_pipe('t16', from_name='p5', to_name='SII4')
        self.map_int.add_pipe('t17', from_name='SII3', to_name='B_ASP')
        self.map_int.add_pipe('t18', from_name='SII4', to_name='AO')
        # add value box
        self.map_int.add_vbox('REG_VL1', 470, 260, size=5, get_value=lambda: Tags.REG1_OUT_REG, prefix='S', suffix='%')
        self.map_int.add_vbox('POS_VL1', 640, 290, size=5, get_value=lambda: Tags.API_POS_VL1, prefix='P', suffix='%')
        self.map_int.add_vbox('REG_VL2', 170, 260, size=5, get_value=lambda: Tags.REG2_OUT_REG, prefix='S', suffix='%')
        self.map_int.add_vbox('POS_VL2', 340, 290, size=5, get_value=lambda: Tags.API_POS_VL2, prefix='P', suffix='%')
        self.map_int.add_vbox('P_AVION', 250, 50, get_value=lambda: Tags.API_P_MINE, prefix='P', suffix='bars')
        self.map_int.add_vbox('P_AO1', 650, 500, get_value=lambda: Tags.API_P_AO1, prefix='P AO1', suffix='bars')
        self.map_int.add_vbox('P_AO2', 650, 530, get_value=lambda: Tags.API_P_AO2, prefix='P AO2', suffix='bars')
        self.map_int.add_vbox('Q_AVION', 400, 110, get_value=lambda: Tags.API_Q_MINE, prefix='Q', suffix='Nm3/h',
                              tk_fmt='{:.0f}')
        # custom widget
        # Pilotage poste
        self.frmConf = tk.Frame(self.map_int.can)
        tk.Label(self.frmConf, text='Etat poste').pack(fill=tk.X, padx=25)
        self.cnfDist = tk.Label(self.frmConf, text='Distant', background=WHITE)
        self.cnfDist.pack(fill=tk.X)
        self.cnfLoc = tk.Label(self.frmConf, text='Local', background=WHITE)
        self.cnfLoc.pack(fill=tk.X)
        self.cnfAU = tk.Label(self.frmConf, text='Arrêt d\'urgence', background=WHITE)
        self.cnfAU.pack(fill=tk.X)
        tk.Label(self.frmConf, text='', background=GRAY).pack(fill=tk.X)
        self.map_int.can.create_window(720, 50, window=self.frmConf)
        # build all
        self.map_int.build()
        # set static valve
        self.map_int.simple_valve.anim('V12', True, False)

    def tab_update(self):
        # update value box
        self.map_int.update_vbox()
        # update simple valves
        self.map_int.simple_valve.tag_anim('B0', Tags.API_POSTE_MARCHE, Tags.API_POSTE_ARRET)
        self.map_int.simple_valve.tag_anim('B1', Tags.API_L1_MARCHE, Tags.API_L1_ARRET)
        self.map_int.simple_valve.tag_anim('B2', Tags.API_L2_MARCHE, Tags.API_L2_ARRET)
        self.map_int.simple_valve.tag_anim('SII3', Tags.API_MODE_I3, Tags.API_MODE_I4)
        self.map_int.simple_valve.tag_anim('SII4', Tags.API_MODE_I4, Tags.API_MODE_I3)
        # update flow valves
        # VL1
        if Tags.API_POS_VL1.err:
            self.map_int.flow_valve.full_set_color('VL1', PINK)
        elif Tags.API_POS_VL1.val < 15.0:
            self.map_int.flow_valve.full_set_color('VL1', RED)
        elif Tags.API_POS_VL1.val < 85.0:
            self.map_int.flow_valve.full_set_color('VL1', WHITE)
        else:
            self.map_int.flow_valve.full_set_color('VL1', GREEN)
        # VL2
        if Tags.API_POS_VL2.err:
            self.map_int.flow_valve.full_set_color('VL2', PINK)
        elif Tags.API_POS_VL2.val < 15.0:
            self.map_int.flow_valve.full_set_color('VL2', RED)
        elif Tags.API_POS_VL2.val < 85.0:
            self.map_int.flow_valve.full_set_color('VL2', WHITE)
        else:
            self.map_int.flow_valve.full_set_color('VL2', GREEN)
        # update config.
        self.cnfDist.configure(background=color_tag_state(Tags.API_TELE))
        self.cnfLoc.configure(background=color_tag_state(Tags.API_LOCAL))
        self.cnfAU.configure(background=color_tag_alarm(Tags.API_MEL_AU))


class TabRegL1(HMITab):
    def __init__(self, notebook, update_ms=500, *args, **kwargs):
        HMITab.__init__(self, notebook, update_ms, *args, **kwargs)
        # Some vars
        self.manu_str = tk.StringVar(value='0.0')
        self.cons_w_str = tk.StringVar(value='0')
        self.cons_p_str = tk.StringVar(value='0')
        self.cons_d_str = tk.StringVar(value='0')
        # Etats régulateur
        self.frmEtatReg = tk.LabelFrame(self, text='Etats régulateur', padx=10, pady=10)
        self.frmEtatReg.grid(row=0, column=0, columnspan=2, padx=5, pady=5, sticky=tk.NSEW)
        self.etat_l = HMIBoolList(self.frmEtatReg, lbl_args={'width': 20}, grid_args={'padx': 20})
        self.etat_l.add('Marche', Tags.REG1_MARCHE)
        self.etat_l.add('Arrêt', Tags.REG1_ARRET)
        self.etat_l.add('Auto Distant', Tags.REG1_AUTO_D)
        self.etat_l.add('Auto Local', Tags.REG1_AUTO_L)
        self.etat_l.add('Manuel', Tags.REG1_MANU)
        self.etat_l.add('Déf. mesure Wobbe', Tags.REG1_DEF_M_WOBBE, alarm=True)
        self.etat_l.add('Déf. mesure PCS', Tags.REG1_DEF_M_PCS, alarm=True)
        self.etat_l.add('Déf. mesure débit', Tags.REG1_DEF_M_DEBIT, alarm=True)
        self.etat_l.add('Err. consigne Wobbe', Tags.REG1_ERR_C_WOBBE, alarm=True)
        self.etat_l.add('Err. consigne PCS', Tags.REG1_ERR_C_PCS, alarm=True)
        self.etat_l.add('Err. consigne débit', Tags.REG1_ERR_C_DEBIT, alarm=True)
        self.etat_l.build()
        # Consignes régulateur
        self.frmConsReg = tk.LabelFrame(self, text='Consignes régulateur', padx=10, pady=10)
        self.frmConsReg.grid(row=0, column=2, padx=5, pady=5, sticky=tk.NSEW)
        self.cons_r = HMIAnalogList(self.frmConsReg, lbl_args={'width': 10})
        self.cons_r.add('Consigne Wobbe active', Tags.REG1_C_WOBBE_ACT, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne Wobbe CSR', Tags.REG1_C_WOBBE_CSR, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne PCS active', Tags.REG1_C_PCS_ACT, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne PCS CSR', Tags.REG1_C_PCS_CSR, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne débit active', Tags.REG1_C_DEBIT_ACT, unit='Nm3/h', fmt='%0.f')
        self.cons_r.add('Consigne débit CSR', Tags.REG1_C_DEBIT_CSR, unit='Nm3/h', fmt='%0.f')
        self.cons_r.build()
        # Mode automatique local
        self.frmAutoReg = tk.LabelFrame(self, text='Mode automatique local', padx=10, pady=10)
        self.frmAutoReg.grid(row=0, column=3, padx=5, pady=5, sticky=tk.NSEW)
        # wobbe
        tk.Label(self.frmAutoReg, text='Consigne Wobbe').grid(row=0, column=0, padx=5, pady=5)
        self.ent_cons_w = tk.Entry(self.frmAutoReg, width='6', justify=tk.RIGHT, textvariable=self.cons_w_str)
        self.ent_cons_w.grid(row=0, column=1, padx=5, pady=5)
        tk.Label(self.frmAutoReg, text='Wh/Nm3').grid(row=0, column=2, padx=5, pady=5)
        self.but_cons_w = tk.Button(self.frmAutoReg, text='Set', command=self.send_cons_w_value)
        self.but_cons_w.grid(row=0, column=3, padx=5, pady=5)
        # pcs
        tk.Label(self.frmAutoReg, text='Consigne PCS').grid(row=1, column=0, padx=5, pady=5)
        self.ent_cons_p = tk.Entry(self.frmAutoReg, width='6', justify=tk.RIGHT, textvariable=self.cons_p_str)
        self.ent_cons_p.grid(row=1, column=1, padx=5, pady=5)
        tk.Label(self.frmAutoReg, text='Wh/Nm3').grid(row=1, column=2, padx=5, pady=5)
        self.but_cons_p = tk.Button(self.frmAutoReg, text='Set', command=self.send_cons_p_value)
        self.but_cons_p.grid(row=1, column=3, padx=5, pady=5)
        # débit
        tk.Label(self.frmAutoReg, text='Consigne débit').grid(row=2, column=0, padx=5, pady=5)
        self.ent_cons_d = tk.Entry(self.frmAutoReg, width='6', justify=tk.RIGHT, textvariable=self.cons_d_str)
        self.ent_cons_d.grid(row=2, column=1, padx=5, pady=5)
        tk.Label(self.frmAutoReg, text='Nm3/h').grid(row=2, column=2, padx=5, pady=5)
        self.but_cons_d = tk.Button(self.frmAutoReg, text='Set', command=self.send_cons_d_value)
        self.but_cons_d.grid(row=2, column=3, padx=5, pady=5)
        # PID menant
        self.frmEtatPid = tk.LabelFrame(self, text='PID menant', padx=10, pady=10)
        self.frmEtatPid.grid(row=1, column=0, padx=5, pady=5, sticky=tk.NSEW)
        self.etat_pid = HMIBoolList(self.frmEtatPid, lbl_args={'width': 10}, grid_args={'padx': 10})
        self.etat_pid.add('Wobbe', Tags.REG1_PID_WOBBE_A)
        self.etat_pid.add('PCS', Tags.REG1_PID_PCS_A)
        self.etat_pid.add('débit', Tags.REG1_PID_DEBIT_A)
        self.etat_pid.build()
        # PID inhibition
        self.frmInhPid = tk.LabelFrame(self, text='PID inhibition', padx=10, pady=10)
        self.frmInhPid.grid(row=1, column=1, padx=5, pady=5, sticky=tk.NSEW)
        self.inh_pid = HMIBoolList(self.frmInhPid, lbl_args={'width': 10}, grid_args={'padx': 10})
        self.inh_pid.add('Wobbe', Tags.REG1_INH_M_WOBBE, alarm=True)
        self.inh_pid.add('PCS', Tags.REG1_INH_M_PCS, alarm=True)
        self.inh_pid.add('débit', Tags.REG1_INH_M_DEBIT, alarm=True)
        self.inh_pid.build()
        # Mesures régulateur
        self.frmMesReg = tk.LabelFrame(self, text='Mesures régulateur', padx=10, pady=10)
        self.frmMesReg.grid(row=1, column=2, rowspan=2, padx=5, pady=5, sticky=tk.NSEW)
        self.mes_r = HMIAnalogList(self.frmMesReg, lbl_args={'width': 10})
        self.mes_r.add('Mesure Wobbe', Tags.REG1_M_WOBBE, unit='Wh/Nm3', fmt='%0.f')
        self.mes_r.add('Mesure PCS', Tags.REG1_M_PCS, unit='Wh/Nm3', fmt='%0.f')
        self.mes_r.add('Mesure débit', Tags.REG1_M_DEBIT, unit='Nm3/h', fmt='%0.f')
        self.mes_r.add('PID Wobbe', Tags.REG1_OUT_PID_WOBBE, unit='%', fmt='%0.2f')
        self.mes_r.add('PID PCS', Tags.REG1_OUT_PID_PCS, unit='%', fmt='%0.2f')
        self.mes_r.add('PID débit', Tags.REG1_OUT_PID_DEBIT, unit='%', fmt='%0.2f')
        self.mes_r.add('Sortie régulateur', Tags.REG1_OUT_REG, unit='%', fmt='%0.2f')
        self.mes_r.build()
        # Divers
        self.frmErr = tk.LabelFrame(self, text='Ecart consigne/mesure', padx=10, pady=10)
        self.frmErr.grid(row=2, column=0, columnspan=2, padx=5, pady=5, sticky=tk.NSEW)
        self.err_l = HMIAnalogList(self.frmErr, lbl_args={'width': 10})
        self.err_l.add('Ecart Wobbe', Tags.REG1_DLT_C_WOBBE, unit='Wh/Nm3', fmt='%0.f')
        self.err_l.add('Ecart PCS', Tags.REG1_DLT_C_PCS, unit='Wh/Nm3', fmt='%0.f')
        self.err_l.add('Ecart débit', Tags.REG1_DLT_C_DEBIT, unit='Nm3/h', fmt='%0.f')
        self.err_l.build()
        # Commande de la sortie du régulateur
        self.frmManuReg = tk.LabelFrame(self, text='Mode manuel', padx=10, pady=10)
        self.frmManuReg.grid(row=1, column=3, padx=5, pady=5, sticky=tk.NSEW)
        tk.Label(self.frmManuReg, text='Sortie').grid(row=0, column=0, padx=5, pady=5)
        self.ent_man = tk.Entry(self.frmManuReg, width='6', justify=tk.RIGHT, textvariable=self.manu_str)
        self.ent_man.grid(row=0, column=1, padx=5, pady=5)
        tk.Label(self.frmManuReg, text='%').grid(row=0, column=2, padx=5, pady=5)
        self.but_man = tk.Button(self.frmManuReg, text='Set', command=self.send_man_value)
        self.but_man.grid(row=0, column=3, padx=5, pady=5)
        # Choix des modes du régulateur
        self.frmModeReg = tk.LabelFrame(self, text='Choix du mode', padx=10, pady=10)
        self.frmModeReg.grid(row=2, column=3, padx=5, pady=5, sticky=tk.NSEW)
        self.mode_l = HMIButtonList(self.frmModeReg, btn_args={'width': 15}, grid_args={'pady': 5})
        self.mode_l.add('mode automatique', tag_valid=Tags.REG1_LOCAL, cmd=self.send_auto_mode,
                        btn_args={'bg': GREEN})
        self.mode_l.add('mode manuel', tag_valid=Tags.REG1_LOCAL, cmd=self.send_man_mode,
                        btn_args={'bg': RED})
        self.mode_l.build()
        # install callback
        self.manu_str.trace('w', self.manu_str_refresh)
        self.cons_w_str.trace('w', self.cons_w_str_refresh)
        self.cons_p_str.trace('w', self.cons_p_str_refresh)
        self.cons_d_str.trace('w', self.cons_d_str_refresh)

    def tab_update(self):
        # refresh widget
        self.etat_l.update()
        self.cons_r.update()
        self.mes_r.update()
        self.err_l.update()
        self.mode_l.update()
        self.etat_pid.update()
        self.inh_pid.update()
        # update manu entry
        self.manu_str_refresh()
        self.cons_w_str_refresh()
        self.cons_p_str_refresh()
        self.cons_d_str_refresh()

    def cons_w_str_refresh(self, *args):
        # update manu entry
        if Tags.REG1_LOCAL.val:
            try:
                if not (11160.0 <= float(self.cons_w_str.get()) <= 13360.0):
                    raise ValueError
                if abs(Tags.REG1_C_WOBBE_ACT.val - float(self.cons_w_str.get())) < 1.0:
                    self.ent_cons_w.config(bg='white')
                else:
                    self.ent_cons_w.config(bg='yellow2')
                self.but_cons_w.configure(state='normal')
            except ValueError:
                self.ent_cons_w.config(bg='red')
                self.but_cons_w.configure(state='disabled')
        else:
            self.ent_cons_w.config(bg='white')
            self.but_cons_w.configure(state='disabled')
            self.cons_w_str.set('%.f' % Tags.REG1_C_WOBBE_ACT.val)

    def send_cons_w_value(self):
        try:
            send_cons = float(self.cons_w_str.get())
            ConfirmDialog(self, title='Confirmation consigne',
                          text='Envoi consigne Wobbe %.f Wh/Nm3 ?' % send_cons,
                          valid_command=lambda: Tags.REG1_W_CONS_W.set(send_cons))
            self.ent_cons_w.config(bg='white')
        except ValueError:
            self.ent_cons_w.config(bg='red')

    def cons_p_str_refresh(self, *args):
        # update manu entry
        if Tags.REG1_LOCAL.val:
            try:
                if not (9100.0 <= float(self.cons_p_str.get()) <= 11100.0):
                    raise ValueError
                if abs(Tags.REG1_C_PCS_ACT.val - float(self.cons_p_str.get())) < 1.0:
                    self.ent_cons_p.config(bg='white')
                else:
                    self.ent_cons_p.config(bg='yellow2')
                self.but_cons_p.configure(state='normal')
            except ValueError:
                self.ent_cons_p.config(bg='red')
                self.but_cons_p.configure(state='disabled')
        else:
            self.ent_cons_p.config(bg='white')
            self.but_cons_p.configure(state='disabled')
            self.cons_p_str.set('%.f' % Tags.REG1_C_PCS_ACT.val)

    def send_cons_p_value(self):
        try:
            send_cons = float(self.cons_p_str.get())
            ConfirmDialog(self, title='Confirmation consigne',
                          text='Envoi consigne PCS %.f Wh/Nm3 ?' % send_cons,
                          valid_command=lambda: Tags.REG1_W_CONS_P.set(send_cons))
            self.ent_cons_p.config(bg='white')
        except ValueError:
            self.ent_cons_p.config(bg='red')

    def cons_d_str_refresh(self, *args):
        # update manu entry
        if Tags.REG1_LOCAL.val:
            try:
                if not (0.0 <= float(self.cons_d_str.get()) <= 25000.0):
                    raise ValueError
                if abs(Tags.REG1_C_DEBIT_ACT.val - float(self.cons_d_str.get())) < 1.0:
                    self.ent_cons_d.config(bg='white')
                else:
                    self.ent_cons_d.config(bg='yellow2')
                self.but_cons_d.configure(state='normal')
            except ValueError:
                self.ent_cons_d.config(bg='red')
                self.but_cons_d.configure(state='disabled')
        else:
            self.ent_cons_d.config(bg='white')
            self.but_cons_d.configure(state='disabled')
            self.cons_d_str.set('%.f' % Tags.REG1_C_DEBIT_ACT.val)

    def send_cons_d_value(self):
        try:
            send_cons = float(self.cons_d_str.get())
            ConfirmDialog(self, title='Confirmation consigne',
                          text='Envoi consigne débit %.f Nm3/h ?' % send_cons,
                          valid_command=lambda: Tags.REG1_W_CONS_D.set(send_cons))
            self.ent_cons_d.config(bg='white')
        except ValueError:
            self.ent_cons_d.config(bg='red')

    def manu_str_refresh(self, *args):
        # update manu entry
        if Tags.REG1_MANU.val:
            try:
                if not (0.0 <= float(self.manu_str.get()) <= 100.0):
                    raise ValueError
                if abs(Tags.REG1_OUT_REG.val - float(self.manu_str.get())) < 1.0:
                    self.ent_man.config(bg='white')
                else:
                    self.ent_man.config(bg='yellow2')
                self.but_man.configure(state='normal')
            except ValueError:
                self.ent_man.config(bg='red')
                self.but_man.configure(state='disabled')
        else:
            self.ent_man.config(bg='white')
            self.but_man.configure(state='disabled')
            self.manu_str.set('%.2f' % Tags.REG1_OUT_REG.val)

    def send_man_value(self):
        try:
            send_cons = float(self.manu_str.get())
            ConfirmDialog(self, title='Confirmation consigne',
                          text='Envoi ouveture VL1 à %.2f %% ?' % send_cons,
                          valid_command=lambda: Tags.REG1_W_OUV_VL.set(send_cons))
            self.ent_man.config(bg='white')
        except ValueError:
            self.ent_man.config(bg='red')

    def send_auto_mode(self):
        ConfirmDialog(self, title='Confirmation mode',
                      text='Passage en mode automatique du régulateur 1 ?',
                      valid_command=lambda: Tags.REG1_MODE_AUTO.set(True))

    def send_man_mode(self):
        ConfirmDialog(self, title='Confirmation mode',
                      text='Passage en mode manuel du régulateur 1 ?',
                      valid_command=lambda: Tags.REG1_MODE_MANU.set(True))


class TabRegL2(HMITab):
    def __init__(self, notebook, update_ms=500, *args, **kwargs):
        HMITab.__init__(self, notebook, update_ms, *args, **kwargs)
        # Some vars
        self.manu_str = tk.StringVar(value='0.0')
        self.cons_w_str = tk.StringVar(value='0')
        self.cons_p_str = tk.StringVar(value='0')
        self.cons_d_str = tk.StringVar(value='0')
        # Etats régulateur
        self.frmEtatReg = tk.LabelFrame(self, text='Etats régulateur', padx=10, pady=10)
        self.frmEtatReg.grid(row=0, column=0, columnspan=2, padx=5, pady=5, sticky=tk.NSEW)
        self.etat_l = HMIBoolList(self.frmEtatReg, lbl_args={'width': 20}, grid_args={'padx': 20})
        self.etat_l.add('Marche', Tags.REG2_MARCHE)
        self.etat_l.add('Arrêt', Tags.REG2_ARRET)
        self.etat_l.add('Auto Distant', Tags.REG2_AUTO_D)
        self.etat_l.add('Auto Local', Tags.REG2_AUTO_L)
        self.etat_l.add('Manuel', Tags.REG2_MANU)
        self.etat_l.add('Déf. mesure Wobbe', Tags.REG2_DEF_M_WOBBE, alarm=True)
        self.etat_l.add('Déf. mesure PCS', Tags.REG2_DEF_M_PCS, alarm=True)
        self.etat_l.add('Déf. mesure débit', Tags.REG2_DEF_M_DEBIT, alarm=True)
        self.etat_l.add('Err. consigne Wobbe', Tags.REG2_ERR_C_WOBBE, alarm=True)
        self.etat_l.add('Err. consigne PCS', Tags.REG2_ERR_C_PCS, alarm=True)
        self.etat_l.add('Err. consigne débit', Tags.REG2_ERR_C_DEBIT, alarm=True)
        self.etat_l.build()
        # Consignes régulateur
        self.frmConsReg = tk.LabelFrame(self, text='Consignes régulateur', padx=10, pady=10)
        self.frmConsReg.grid(row=0, column=2, padx=5, pady=5, sticky=tk.NSEW)
        self.cons_r = HMIAnalogList(self.frmConsReg, lbl_args={'width': 10})
        self.cons_r.add('Consigne Wobbe active', Tags.REG2_C_WOBBE_ACT, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne Wobbe CSR', Tags.REG2_C_WOBBE_CSR, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne PCS active', Tags.REG2_C_PCS_ACT, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne PCS CSR', Tags.REG2_C_PCS_CSR, unit='Wh/Nm3', fmt='%0.f')
        self.cons_r.add('Consigne débit active', Tags.REG2_C_DEBIT_ACT, unit='Nm3/h', fmt='%0.f')
        self.cons_r.add('Consigne débit CSR', Tags.REG2_C_DEBIT_CSR, unit='Nm3/h', fmt='%0.f')
        self.cons_r.build()
        # Mode automatique local
        self.frmAutoReg = tk.LabelFrame(self, text='Mode automatique local', padx=10, pady=10)
        self.frmAutoReg.grid(row=0, column=3, padx=5, pady=5, sticky=tk.NSEW)
        self.AutoReglbl = tk.Label(self.frmAutoReg, font='bold', justify=tk.CENTER,
                                   text='pilotage via facade du régulateur')
        self.AutoReglbl.pack(fill=tk.BOTH, expand=tk.TRUE)
        # wobbe
        # tk.Label(self.frmAutoReg, text='Consigne Wobbe').grid(row=0, column=0, padx=5, pady=5)
        # self.ent_cons_w = tk.Entry(self.frmAutoReg, width='6', justify=tk.RIGHT, textvariable=self.cons_w_str)
        # self.ent_cons_w.grid(row=0, column=1, padx=5, pady=5)
        # tk.Label(self.frmAutoReg, text='Wh/Nm3').grid(row=0, column=2, padx=5, pady=5)
        # self.but_cons_w = tk.Button(self.frmAutoReg, text='Set', command=self.send_cons_w_value)
        # self.but_cons_w.grid(row=0, column=3, padx=5, pady=5)
        # # pcs
        # tk.Label(self.frmAutoReg, text='Consigne PCS').grid(row=1, column=0, padx=5, pady=5)
        # self.ent_cons_p = tk.Entry(self.frmAutoReg, width='6', justify=tk.RIGHT, textvariable=self.cons_p_str)
        # self.ent_cons_p.grid(row=1, column=1, padx=5, pady=5)
        # tk.Label(self.frmAutoReg, text='Wh/Nm3').grid(row=1, column=2, padx=5, pady=5)
        # self.but_cons_p = tk.Button(self.frmAutoReg, text='Set', command=self.send_cons_p_value)
        # self.but_cons_p.grid(row=1, column=3, padx=5, pady=5)
        # # débit
        # tk.Label(self.frmAutoReg, text='Consigne débit').grid(row=2, column=0, padx=5, pady=5)
        # self.ent_cons_d = tk.Entry(self.frmAutoReg, width='6', justify=tk.RIGHT, textvariable=self.cons_d_str)
        # self.ent_cons_d.grid(row=2, column=1, padx=5, pady=5)
        # tk.Label(self.frmAutoReg, text='Nm3/h').grid(row=2, column=2, padx=5, pady=5)
        # self.but_cons_d = tk.Button(self.frmAutoReg, text='Set', command=self.send_cons_d_value)
        # self.but_cons_d.grid(row=2, column=3, padx=5, pady=5)
        # PID menant
        self.frmEtatPid = tk.LabelFrame(self, text='PID menant', padx=10, pady=10)
        self.frmEtatPid.grid(row=1, column=0, padx=5, pady=5, sticky=tk.NSEW)
        self.etat_pid = HMIBoolList(self.frmEtatPid, lbl_args={'width': 10}, grid_args={'padx': 10})
        self.etat_pid.add('Wobbe', Tags.REG2_PID_WOBBE_A)
        self.etat_pid.add('PCS', Tags.REG2_PID_PCS_A)
        self.etat_pid.add('débit', Tags.REG2_PID_DEBIT_A)
        self.etat_pid.build()
        # PID inhibition
        self.frmInhPid = tk.LabelFrame(self, text='PID inhibition', padx=10, pady=10)
        self.frmInhPid.grid(row=1, column=1, padx=5, pady=5, sticky=tk.NSEW)
        self.inh_pid = HMIBoolList(self.frmInhPid, lbl_args={'width': 10}, grid_args={'padx': 10})
        self.inh_pid.add('Wobbe', Tags.REG2_INH_M_WOBBE, alarm=True)
        self.inh_pid.add('PCS', Tags.REG2_INH_M_PCS, alarm=True)
        self.inh_pid.add('débit', Tags.REG2_INH_M_DEBIT, alarm=True)
        self.inh_pid.build()
        # Mesures régulateur
        self.frmMesReg = tk.LabelFrame(self, text='Mesures régulateur', padx=10, pady=10)
        self.frmMesReg.grid(row=1, column=2, rowspan=2, padx=5, pady=5, sticky=tk.NSEW)
        self.mes_r = HMIAnalogList(self.frmMesReg, lbl_args={'width': 10})
        self.mes_r.add('Mesure Wobbe', Tags.REG2_M_WOBBE, unit='Wh/Nm3', fmt='%0.f')
        self.mes_r.add('Mesure PCS', Tags.REG2_M_PCS, unit='Wh/Nm3', fmt='%0.f')
        self.mes_r.add('Mesure débit', Tags.REG2_M_DEBIT, unit='Nm3/h', fmt='%0.f')
        self.mes_r.add('PID Wobbe', Tags.REG2_OUT_PID_WOBBE, unit='%', fmt='%0.2f')
        self.mes_r.add('PID PCS', Tags.REG2_OUT_PID_PCS, unit='%', fmt='%0.2f')
        self.mes_r.add('PID débit', Tags.REG2_OUT_PID_DEBIT, unit='%', fmt='%0.2f')
        self.mes_r.add('Sortie régulateur', Tags.REG2_OUT_REG, unit='%', fmt='%0.2f')
        self.mes_r.build()
        # Divers
        self.frmErr = tk.LabelFrame(self, text='Ecart consigne/mesure', padx=10, pady=10)
        self.frmErr.grid(row=2, column=0, columnspan=2, padx=5, pady=5, sticky=tk.NSEW)
        self.err_l = HMIAnalogList(self.frmErr, lbl_args={'width': 10})
        self.err_l.add('Ecart Wobbe', Tags.REG2_DLT_C_WOBBE, unit='Wh/Nm3', fmt='%0.f')
        self.err_l.add('Ecart PCS', Tags.REG2_DLT_C_PCS, unit='Wh/Nm3', fmt='%0.f')
        self.err_l.add('Ecart débit', Tags.REG2_DLT_C_DEBIT, unit='Nm3/h', fmt='%0.f')
        self.err_l.build()
        # Commande de la sortie du régulateur
        self.frmManuReg = tk.LabelFrame(self, text='Mode manuel', padx=10, pady=10)
        self.frmManuReg.grid(row=1, column=3, padx=5, pady=5, sticky=tk.NSEW)
        self.Manlbl = tk.Label(self.frmManuReg, font='bold', justify=tk.CENTER,
                               text='pilotage via facade du régulateur')
        self.Manlbl.pack(fill=tk.BOTH, expand=tk.TRUE)
        # tk.Label(self.frmManuReg, text='Sortie').grid(row=0, column=0, padx=5, pady=5)
        # self.ent_man = tk.Entry(self.frmManuReg, width='6', justify=tk.RIGHT, textvariable=self.manu_str)
        # self.ent_man.grid(row=0, column=1, padx=5, pady=5)
        # tk.Label(self.frmManuReg, text='%').grid(row=0, column=2, padx=5, pady=5)
        # self.but_man = tk.Button(self.frmManuReg, text='Set', command=self.send_man_value)
        # self.but_man.grid(row=0, column=3, padx=5, pady=5)
        # Choix des modes du régulateur
        self.frmModeReg = tk.LabelFrame(self, text='Choix du mode', padx=10, pady=10)
        self.frmModeReg.grid(row=2, column=3, padx=5, pady=5, sticky=tk.NSEW)
        self.Manlbl = tk.Label(self.frmModeReg, font='bold', justify=tk.CENTER,
                               text='pilotage via facade du régulateur')
        self.Manlbl.pack(fill=tk.BOTH, expand=tk.TRUE)
        # self.mode_l = HMIButtonList(self.frmManuReg, btn_args={'width': 15}, grid_args={'pady': 5})
        # self.mode_l.add('mode automatique', tag_valid=Tags.REG2_LOCAL, cmd=self.send_auto_mode,
        #                 btn_args={'bg': GREEN})
        # self.mode_l.add('mode manuel', tag_valid=Tags.REG2_LOCAL, cmd=self.send_man_mode,
        #                 btn_args={'bg': RED})
        # self.mode_l.build()
        # install callback
        # self.manu_str.trace('w', self.manu_str_refresh)
        # self.cons_w_str.trace('w', self.cons_w_str_refresh)
        # self.cons_p_str.trace('w', self.cons_p_str_refresh)
        # self.cons_d_str.trace('w', self.cons_d_str_refresh)

    def tab_update(self):
        # refresh widget
        self.etat_l.update()
        self.cons_r.update()
        self.etat_pid.update()
        self.inh_pid.update()
        self.err_l.update()
        self.mes_r.update()
        # self.mode_l.update()
        # update manu entry
        # self.manu_str_refresh()
        # self.cons_w_str_refresh()
        # self.cons_p_str_refresh()
        # self.cons_d_str_refresh()

    # def cons_w_str_refresh(self, *args):
    #     # update manu entry
    #     if Tags.REG2_LOCAL.val:
    #         try:
    #             if not (11160.0 <= float(self.cons_w_str.get()) <= 13360.0):
    #                 raise ValueError
    #             if abs(Tags.REG2_C_WOBBE_ACT.val - float(self.cons_w_str.get())) < 1.0:
    #                 self.ent_cons_w.config(bg='white')
    #             else:
    #                 self.ent_cons_w.config(bg='yellow2')
    #             self.but_cons_w.configure(state='normal')
    #         except ValueError:
    #             self.ent_cons_w.config(bg='red')
    #             self.but_cons_w.configure(state='disabled')
    #     else:
    #         self.ent_cons_w.config(bg='white')
    #         self.but_cons_w.configure(state='disabled')
    #         self.cons_w_str.set('%.f' % Tags.REG2_C_WOBBE_ACT.val)
    #
    # def send_cons_w_value(self):
    #     try:
    #         send_cons = float(self.cons_w_str.get())
    #         ConfirmDialog(self, title='Confirmation consigne',
    #                       text='Envoi consigne Wobbe %.f Wh/Nm3 ?' % send_cons,
    #                       valid_command=lambda: Tags.REG2_W_CONS_W.set(send_cons))
    #         self.ent_cons_w.config(bg='white')
    #     except ValueError:
    #         self.ent_cons_w.config(bg='red')
    #
    # def cons_p_str_refresh(self, *args):
    #     # update manu entry
    #     if Tags.REG2_LOCAL.val:
    #         try:
    #             if not (9100.0 <= float(self.cons_p_str.get()) <= 11100.0):
    #                 raise ValueError
    #             if abs(Tags.REG2_C_PCS_ACT.val - float(self.cons_p_str.get())) < 1.0:
    #                 self.ent_cons_p.config(bg='white')
    #             else:
    #                 self.ent_cons_p.config(bg='yellow2')
    #             self.but_cons_p.configure(state='normal')
    #         except ValueError:
    #             self.ent_cons_p.config(bg='red')
    #             self.but_cons_p.configure(state='disabled')
    #     else:
    #         self.ent_cons_p.config(bg='white')
    #         self.but_cons_p.configure(state='disabled')
    #         self.cons_p_str.set('%.f' % Tags.REG2_C_PCS_ACT.val)
    #
    # def send_cons_p_value(self):
    #     try:
    #         send_cons = float(self.cons_p_str.get())
    #         ConfirmDialog(self, title='Confirmation consigne',
    #                       text='Envoi consigne PCS %.f Wh/Nm3 ?' % send_cons,
    #                       valid_command=lambda: Tags.REG2_W_CONS_P.set(send_cons))
    #         self.ent_cons_p.config(bg='white')
    #     except ValueError:
    #         self.ent_cons_p.config(bg='red')
    #
    # def cons_d_str_refresh(self, *args):
    #     # update manu entry
    #     if Tags.REG2_LOCAL.val:
    #         try:
    #             if not (0.0 <= float(self.cons_d_str.get()) <= 25000.0):
    #                 raise ValueError
    #             if abs(Tags.REG2_C_DEBIT_ACT.val - float(self.cons_d_str.get())) < 1.0:
    #                 self.ent_cons_d.config(bg='white')
    #             else:
    #                 self.ent_cons_d.config(bg='yellow2')
    #             self.but_cons_d.configure(state='normal')
    #         except ValueError:
    #             self.ent_cons_d.config(bg='red')
    #             self.but_cons_d.configure(state='disabled')
    #     else:
    #         self.ent_cons_d.config(bg='white')
    #         self.but_cons_d.configure(state='disabled')
    #         self.cons_d_str.set('%.f' % Tags.REG2_C_DEBIT_ACT.val)
    #
    # def send_cons_d_value(self):
    #     try:
    #         send_cons = float(self.cons_d_str.get())
    #         ConfirmDialog(self, title='Confirmation consigne',
    #                       text='Envoi consigne débit %.f Nm3/h ?' % send_cons,
    #                       valid_command=lambda: Tags.REG2_W_CONS_D.set(send_cons))
    #         self.ent_cons_d.config(bg='white')
    #     except ValueError:
    #         self.ent_cons_d.config(bg='red')
    #
    # def manu_str_refresh(self, *args):
    #     # update manu entry
    #     if Tags.REG2_AUTO_MANU.val:
    #         try:
    #             if not (0.0 <= float(self.manu_str.get()) <= 100.0):
    #                 raise ValueError
    #             if abs(Tags.REG2_OUT_REG.val - float(self.manu_str.get())) < 1.0:
    #                 self.ent_man.config(bg='white')
    #             else:
    #                 self.ent_man.config(bg='yellow2')
    #             self.but_man.configure(state='normal')
    #         except ValueError:
    #             self.ent_man.config(bg='red')
    #             self.but_man.configure(state='disabled')
    #     else:
    #         self.ent_man.config(bg='white')
    #         self.but_man.configure(state='disabled')
    #         self.manu_str.set('%.2f' % Tags.REG2_OUT_REG.val)
    #
    # def send_man_value(self):
    #     try:
    #         send_cons = float(self.manu_str.get())
    #         ConfirmDialog(self, title='Confirmation consigne',
    #                       text='Envoi ouveture VL2 à %.2f %% ?' % send_cons,
    #                       valid_command=lambda: Tags.REG2_W_OUV_VL.set(send_cons))
    #         self.ent_man.config(bg='white')
    #     except ValueError:
    #         self.ent_man.config(bg='red')
    #
    # def send_auto_mode(self):
    #     ConfirmDialog(self, title='Confirmation mode',
    #                   text='Passage en mode automatique du régulateur 2 ?',
    #                   valid_command=lambda: Tags.REG2_MODE_AUTO.set(True))
    #
    # def send_man_mode(self):
    #     ConfirmDialog(self, title='Confirmation mode',
    #                   text='Passage en mode manuel du régulateur 2 ?',
    #                   valid_command=lambda: Tags.REG2_MODE_MANU.set(True))


class TabValues(HMITab):
    def __init__(self, notebook, update_ms=500, *args, **kwargs):
        HMITab.__init__(self, notebook, update_ms, *args, **kwargs)
        # Mesures 1
        self.frmMes1 = tk.LabelFrame(self, text='Mesures Wobbe (Wh/Nm3)', padx=10, pady=10)
        self.frmMes1.grid(row=0, column=0, padx=5, pady=5, sticky=tk.NSEW)
        self.mes_list_1 = HMIAnalogList(self.frmMes1, lbl_args={'width': 10})
        self.mes_list_1.add('C4', Tags.API_WBE_C4, fmt='%.f')
        self.mes_list_1.add('GNY', Tags.API_WBE_GNY, fmt='%.f')
        self.mes_list_1.add('Reg. L1', Tags.API_WBE_REG_L1, fmt='%.f')
        self.mes_list_1.add('Sec. L1', Tags.API_WBE_SEC_L1, fmt='%.f')
        self.mes_list_1.add('Reg. L2', Tags.API_WBE_REG_L2, fmt='%.f')
        self.mes_list_1.add('Sec. L2', Tags.API_WBE_SEC_L2, fmt='%.f')
        self.mes_list_1.build()
        # Mesures 2
        self.frmMes2 = tk.LabelFrame(self, text='Mesures PCS (Wh/Nm3)', padx=10, pady=10)
        self.frmMes2.grid(row=0, column=1, padx=5, pady=5, sticky=tk.NSEW)
        self.mes_list_2 = HMIAnalogList(self.frmMes2, lbl_args={'width': 10})
        self.mes_list_2.add('PCS C4', Tags.API_PCS_C4, fmt='%.f')
        self.mes_list_2.add('PCS GNY', Tags.API_PCS_GNY, fmt='%.f')
        self.mes_list_2.add('PCS L1', Tags.API_PCS_L1, fmt='%.f')
        self.mes_list_2.add('PCS L2', Tags.API_PCS_L2, fmt='%.f')
        self.mes_list_2.build()
        # Mesures 3
        self.frmMes3 = tk.LabelFrame(self, text='Mesures divers', padx=10, pady=10)
        self.frmMes3.grid(row=0, column=2, padx=5, pady=5, sticky=tk.NSEW)
        self.mes_list_3 = HMIAnalogList(self.frmMes3, lbl_args={'width': 10})
        self.mes_list_3.add('P Mine', Tags.API_P_MINE, unit='bars', fmt='%.2f')
        self.mes_list_3.add('Q Mine', Tags.API_Q_MINE, unit='Nm3/h', fmt='%.f')
        self.mes_list_3.add('P AO1', Tags.API_P_AO1, unit='bars', fmt='%.2f')
        self.mes_list_3.add('P AO2', Tags.API_P_AO2, unit='bars', fmt='%.2f')
        self.mes_list_3.add('Q annubar I3', Tags.API_Q_ANNU, unit='Nm3/h', fmt='%.f')
        self.mes_list_3.add('Pos. VL L1', Tags.API_POS_VL1, unit='%', fmt='%.2f')
        self.mes_list_3.add('Pos. VL L2', Tags.API_POS_VL2, unit='%', fmt='%.2f')
        self.mes_list_3.build()
        # Mesures ratio
        self.frmRatio = tk.LabelFrame(self, text='Mesures API Ratio', padx=10, pady=10)
        self.frmRatio.grid(row=1, column=0, padx=5, pady=5, sticky=tk.NSEW)
        self.mes_list_4 = HMIAnalogList(self.frmRatio, lbl_args={'width': 10})
        self.mes_list_4.add('PCS virtuel', Tags.RATIO_PCS_VTL, unit='Wh/Nm3', fmt='%.f')
        self.mes_list_4.add('Wobbe virtuel', Tags.RATIO_WBE_VTL, unit='Wh/Nm3', fmt='%.f')
        self.mes_list_4.add('Débit AE 1+2', Tags.RATIO_Q_AE_VTL, unit='Nm3/h', fmt='%.f')
        self.mes_list_4.build()

    def tab_update(self):
        self.mes_list_1.update()
        self.mes_list_2.update()
        self.mes_list_3.update()
        self.mes_list_4.update()


class TabAlarms(HMITab):
    def __init__(self, notebook, update_ms=500, *args, **kwargs):
        HMITab.__init__(self, notebook, update_ms, *args, **kwargs)
        # Calibration des analyseurs
        self.frmCalibAnl = tk.LabelFrame(self, text='Calibration des analyseurs', padx=10, pady=10)
        self.frmCalibAnl.grid(row=0, column=0, padx=5, pady=5, sticky=tk.NSEW)
        self.cal_anl_list = HMIBoolList(self.frmCalibAnl, lbl_args={'width': 20})
        self.cal_anl_list.add('Securité L1', Tags.API_ANL_SEC_L1_CAL, alarm=False)
        self.cal_anl_list.add('Régulation L1', Tags.API_ANL_REG_L1_CAL, alarm=False)
        self.cal_anl_list.add('Securité L2', Tags.API_ANL_SEC_L2_CAL, alarm=False)
        self.cal_anl_list.add('Régulation L2', Tags.API_ANL_REG_L2_CAL, alarm=False)
        self.cal_anl_list.add('C4', Tags.API_ANL_C4_CAL, alarm=False)
        self.cal_anl_list.add('Gournay', Tags.API_ANL_GNY_CAL, alarm=False)
        self.cal_anl_list.build()
        # Défaut des analyseurs
        self.frmDefAnl = tk.LabelFrame(self, text='Défaut des analyseurs', padx=10, pady=10)
        self.frmDefAnl.grid(row=0, column=1, padx=5, pady=5, sticky=tk.NSEW)
        self.def_anl_list = HMIBoolList(self.frmDefAnl, lbl_args={'width': 20})
        self.def_anl_list.add('Securité L1', Tags.API_ANL_SEC_L1_DEF, alarm=True)
        self.def_anl_list.add('Régulation L1', Tags.API_ANL_REG_L1_DEF, alarm=True)
        self.def_anl_list.add('Securité L2', Tags.API_ANL_SEC_L2_DEF, alarm=True)
        self.def_anl_list.add('Régulation L2', Tags.API_ANL_REG_L2_DEF, alarm=True)
        self.def_anl_list.add('C4', Tags.API_ANL_C4_DEF, alarm=True)
        self.def_anl_list.add('Gournay', Tags.API_ANL_GNY_DEF, alarm=True)
        self.def_anl_list.build()
        # Inhibitions
        self.frmInh = tk.LabelFrame(self, text='Inhibitions', padx=10, pady=10)
        self.frmInh.grid(row=0, column=2, padx=5, pady=5, sticky=tk.NSEW)
        self.inh_list = HMIBoolList(self.frmInh, lbl_args={'width': 20})
        self.inh_list.add('Ligne 1 (PCS/Wobbe)', Tags.API_SEC_L1_INH, alarm=True)
        self.inh_list.add('Ligne 2 (PCS/Wobbe)', Tags.API_SEC_L2_INH, alarm=True)
        self.inh_list.add('Q Mine', Tags.API_Q_MINE_INH, alarm=True)
        self.inh_list.add('Q AO', Tags.API_Q_AO_INH, alarm=True)
        self.inh_list.add('Q AE', Tags.API_Q_AE_INH, alarm=True)
        self.inh_list.add('Q Annubar I3', Tags.API_Q_ANNU_INH, alarm=True)
        self.inh_list.add('API ratio', Tags.API_RATIO_INH, alarm=True)
        self.inh_list.build()
        # ATD/Feu
        self.frmCentrale = tk.LabelFrame(self, text='Centrale ATD/Feu', padx=10, pady=10)
        self.frmCentrale.grid(row=1, column=3, padx=5, pady=5, sticky=tk.NSEW)
        self.centrale_list = HMIBoolList(self.frmCentrale, lbl_args={'width': 20})
        self.centrale_list.add('Défaut centrale', Tags.API_DEF_CENT, alarm=True)
        self.centrale_list.add('Etalonnage centrale', Tags.API_ETL_CENT, alarm=True)
        self.centrale_list.add('ATD stade 1', Tags.API_DEF_ATD1, alarm=True)
        self.centrale_list.add('ATD stade 2', Tags.API_DEF_ATD2, alarm=True)
        self.centrale_list.add('Manque O2 stade 1', Tags.API_DEF_O2_1, alarm=True)
        self.centrale_list.add('Manque O2 stade 2', Tags.API_DEF_O2_2, alarm=True)
        self.centrale_list.add('Feu stade 1', Tags.API_DEF_FEU_1, alarm=True)
        self.centrale_list.add('Feu stade 2', Tags.API_DEF_FEU_2, alarm=True)
        self.centrale_list.build()
        # Alarmes mélangeur
        self.frmAlr = tk.LabelFrame(self, text='Alarmes mélangeur', padx=10, pady=10)
        self.frmAlr.grid(row=1, column=0, padx=5, pady=5, sticky=tk.NSEW)
        self.alr_list = HMIBoolList(self.frmAlr, lbl_args={'width': 20})
        self.alr_list.add('Wobbe L1 -', Tags.API_WBE_L1_M)
        self.alr_list.add('PCS L1 -', Tags.API_PCS_L1_M)
        self.alr_list.add('Wobbe L2 -', Tags.API_WBE_L2_M)
        self.alr_list.add('PCS L2 -', Tags.API_PCS_L2_M)
        self.alr_list.add('Wobbe virtuel -', Tags.API_WBE_VTL_M)
        self.alr_list.add('PCS virtuel -', Tags.API_PCS_VTL_M)
        self.alr_list.add('Q AO -', Tags.API_Q_AO_M)
        self.alr_list.add('Q AE -', Tags.API_Q_AE_M)
        self.alr_list.build()
        # Défauts mélangeur
        self.frmDef = tk.LabelFrame(self, text='Défaut mélangeur', padx=10, pady=10)
        self.frmDef.grid(row=1, column=1, padx=5, pady=5, sticky=tk.NSEW)
        self.def_list = HMIBoolList(self.frmDef, lbl_args={'width': 20})
        self.def_list.add('Wobbe L1 --', Tags.API_WBE_L1_MM, alarm=True)
        self.def_list.add('PCS L1 --', Tags.API_PCS_L1_MM, alarm=True)
        self.def_list.add('Wobbe L2 --', Tags.API_WBE_L2_MM, alarm=True)
        self.def_list.add('PCS L2 --', Tags.API_PCS_L2_MM, alarm=True)
        self.def_list.add('Wobbe virtuel --', Tags.API_WBE_VTL_MM, alarm=True)
        self.def_list.add('PCS virtuel --', Tags.API_PCS_VTL_MM, alarm=True)
        self.def_list.add('Q AO --', Tags.API_Q_AO_MM, alarm=True)
        self.def_list.add('Q AE --', Tags.API_Q_AE_MM, alarm=True)
        self.def_list.add('Q Annubar --', Tags.API_Q_ANNU_MM, alarm=True)
        self.def_list.add('Q Mine ++', Tags.API_Q_MINE_PP, alarm=True)
        self.def_list.build()
        # Défauts
        self.frmEnergie = tk.LabelFrame(self, text='Défauts', padx=10, pady=10)
        self.frmEnergie.grid(row=1, column=2, padx=5, pady=5, sticky=tk.NSEW)
        self.energie_list = HMIBoolList(self.frmEnergie, lbl_args={'width': 25})
        self.energie_list.add('Absence EDF', Tags.API_DEF_EDF, alarm=True)
        self.energie_list.add('Défaut chargeur', Tags.API_DEF_CHG_24V, alarm=True)
        self.energie_list.add('Défaut disj. labo', Tags.API_ABS_U_AV_DJ, alarm=True)
        self.energie_list.add('Défaut Relais à seuils', Tags.API_REL_DEF, alarm=True)
        self.energie_list.add('BP Arrêt urgence mél.', Tags.API_MEL_AU, alarm=True)
        self.energie_list.add('BP Arrêt urgence DI/DG', Tags.API_AU_DIDG, alarm=True)
        self.energie_list.add('Défaut mesure/consigne L1', Tags.API_DEF_MES_CON_L1, alarm=True)
        self.energie_list.add('Défaut mesure/consigne L2', Tags.API_DEF_MES_CON_L2, alarm=True)
        self.energie_list.build()

    def tab_update(self):
        self.energie_list.update()
        self.centrale_list.update()
        self.cal_anl_list.update()
        self.def_anl_list.update()
        self.alr_list.update()
        self.def_list.update()
        self.inh_list.update()


class HMIToolbar(tk.Frame):
    def __init__(self, tk_app, update_ms=500, *args, **kwargs):
        tk.Frame.__init__(self, tk_app, *args, **kwargs)
        self.tk_app = tk_app
        self.update_ms = update_ms
        # build toolbar
        self.butAPI = tk.Button(self, text='T-Box API', relief=tk.SUNKEN,
                                state='disabled', disabledforeground='black')
        self.butAPI.pack(side=tk.LEFT)
        self.butRatio = tk.Button(self, text='T-Box Ratio', relief=tk.SUNKEN,
                                  state='disabled', disabledforeground='black')
        self.butRatio.pack(side=tk.LEFT)
        self.butReg1 = tk.Button(self, text='T-Box REG L1', relief=tk.SUNKEN,
                                 state='disabled', disabledforeground='black')
        self.butReg1.pack(side=tk.LEFT)
        self.butReg2 = tk.Button(self, text='T-Box REG L2', relief=tk.SUNKEN,
                                 state='disabled', disabledforeground='black')
        self.butReg2.pack(side=tk.LEFT)
        self.lblDate = tk.Label(self, text='', font=('TkDefaultFont', 12))
        self.lblDate.pack(side=tk.RIGHT)
        self.pack(side=tk.BOTTOM, fill=tk.X)
        # setup auto-refresh of notebook tab (on-visibility and every update_ms)
        self.bind('<Visibility>', lambda evt: self.tab_update())
        self._tab_update()

    def _tab_update(self):
        self.tab_update()
        self.master.after(self.update_ms, self._tab_update)

    def tab_update(self):
        self.butAPI.configure(background=GREEN if Devices.tbx_api.connected else PINK)
        self.butRatio.configure(background=GREEN if Devices.tbx_ratio.connected else PINK)
        self.butReg1.configure(background=GREEN if Devices.tbx_reg1.connected else PINK)
        # self.butReg2.configure(background=GREEN if Devices.tbx_reg2.connected else PINK)
        self.lblDate.configure(text=time.strftime('%H:%M:%S %d/%m/%Y'))


class HMIApp(tk.Tk):
    def __init__(self, *args, **kwargs):
        tk.Tk.__init__(self, *args, **kwargs)
        # configure main window
        self.wm_title('Arleux mélangeur')
        # self.attributes('-fullscreen', True)
        # self.geometry('800x600')
        # periodic tags update
        self.do_every(Tags.update_tags, every_ms=500)
        # build a notebook with tabs
        self.note = ttk.Notebook(self)
        self.tab_syno = TabSyno(self.note)
        self.tab_reg_l1 = TabRegL1(self.note)
        self.tab_reg_l2 = TabRegL2(self.note)
        self.tab_reg_l2 = TabRegL2(self.note)
        self.tab_values = TabValues(self.note)
        self.tab_alarms = TabAlarms(self.note)
        self.note.add(self.tab_syno, text='Synoptique (F1)')
        self.note.add(self.tab_reg_l1, text='Régulation Ligne 1 (F2)')
        self.note.add(self.tab_reg_l2, text='Régulation Ligne 2 (F3)')
        self.note.add(self.tab_values, text='Mesures (F4)')
        self.note.add(self.tab_alarms, text='Etats/Alarmes (F5)')
        self.note.pack(fill=tk.BOTH, expand=True)
        # defaut selected tab
        self.note.select(self.tab_syno)
        # bind function keys to tabs
        self.bind('<F1>', lambda evt: self.note.select(self.tab_syno))
        self.bind('<F2>', lambda evt: self.note.select(self.tab_reg_l1))
        self.bind('<F3>', lambda evt: self.note.select(self.tab_reg_l2))
        self.bind('<F4>', lambda evt: self.note.select(self.tab_values))
        self.bind('<F5>', lambda evt: self.note.select(self.tab_alarms))
        # build toolbar
        self.toolbar = HMIToolbar(self, update_ms=500)

    def do_every(self, do_cmd, every_ms=1000):
        do_cmd()
        self.after(every_ms, lambda: self.do_every(do_cmd, every_ms=every_ms))


if __name__ == '__main__':
    # main Tk App
    app = HMIApp()
    app.mainloop()
